changeLogFile: D:/projects/gemini-site/db/changelog.xml
url: jdbc:sqlite:D:/projects/gemini-site/db/my_portfolio.db
driver: org.sqlite.JDBC
# Шлях до файлу драйвера
classpath: D:\Programs\liquibase\bat