name: CI Check
on: [push, pull_request] # Запускать при пуше и создании PR

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Копируем код в облако

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install # Устанавливаем линтер в облаке

      - name: Run Linter
        run: npm run lint # Запускаем нашу проверку