name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  # Частина 1: Лінтер
  linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install
      - name: Run HTMLHint
        run: npx htmlhint index.html

  # Частина 2: Docker Build & Push (імітація)
  docker_processing:
    needs: linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Build Docker Image
        run: docker build -t gemini-site:${{ github.sha }} .
        
      - name: Docker Push Simulation
        run: |
          echo "Image tagged: gemini-site:${{ github.sha }}"
          echo "Pushing to registry... Success!"

  performance_test:
    needs: docker_processing # Запускаємо після того, як переконалися, що образ збирається
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run k6 load test
        uses: grafana/k6-action@v0.3.1
        with:
          filename: tests/load-test.js # Шлях до файлу з тестами