name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  # Частина 1: Лінтер
  linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install
      - name: Run HTMLHint
        run: npx htmlhint index.html

  # Частина 2: Docker Build & Push (імітація для лаби)
  docker_processing:
    needs: linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Build Docker Image
        run: docker build -t gemini-site:${{ github.sha }} .
        
      - name: Docker Push Simulation
        run: |
          echo "Image tagged: gemini-site:${{ github.sha }}"
          echo "Pushing to registry... Success!"